# App Config
app:
  plan_path: "path.xlsx"
  review_path: "review.xlsx"
# Server Config
server:
  host: "localhost"
  port: 8080
  token_secret: "YOUR SECRET"
  static_path: "../../web"
  html_glob_path: "../../web/html/*.html"
#Redis Config
redis:
  host: ""
  port: 6379
#Updater Config
updater:
  download_path: "YOUR PATH"
  selenium_path: "YOUR PATH"
  browser_mode: "default" # default or headless
  port: 9515
  huawei_login: "login"
  huawei_password: "pass"