# App Config
app:
  plan_path: "plan%s.xlsx" # template path to plan file 
  review_path: "review%s.xlsx" # template path to review file
# Server Config
server:
  host: "localhost" # app host
  port: 8080 # app port
  token_secret: "YOUR SECRET" # random string for jwt tokens
  static_path: "../../web" # path to app static files
  html_glob_path: "../../web/html/*.html" # glob of app html
#Redis Config
redis:
  host: "" # redis host
  port: 6379 # redis port 
#Updater Config
updater:
  download_path: "" # path to your default download dir
  selenium_path: "C:/Drivers/chromedriver.exe" # path to selenium driver
  browser_mode: "default" # default or headless
  port: 9515 # selenium server port
  huawei_projects:
    -
      huawei_login: "login"
      huawei_password: "pass"
      project_id: "56A0A8L"